#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-latest-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: v1.3.2
      extension_name: teradata
      ci_tools_version: main
      vcpkg_commit: ce613c41372b23b1f51333815feb3edd87ef8a8b
      # Only build for "linux_amd64", "linux_arm64", "osx_arm64", "osx_amd64", "windows_amd64"
      exclude_archs: linux_amd64_musl;windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads
      test_config: >
        {"test_env_variables":
          {
            "TD_DB": "${{ vars.TD_DB }}"
          }
        }
    secrets:
      TD_LOGON: ${{ secrets.TD_LOGON }}

  duckdb-latest-deploy:
    name: Deploy extension binaries
    needs: duckdb-latest-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@main
    secrets: inherit
    with:
      duckdb_version: v1.3.2
      ci_tools_version: main
      extension_name: teradata
      deploy_latest: ${{ startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/main' }}